### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by jcreamer898** [lonelyplanet/backpack-ui#149]
### User Story

As a user I want a Modal component so that I can have content pop over the screen

### Acceptance Criteria
* It should be responsive for mobile and desktop
* It should be full screen on mobile

**Comment by thomasthesecond** [comment]
We've got Modal for desktop

https://github.com/lonelyplanet/backpack-ui/blob/master/src/components/modal/index.jsx

and Takeover for mobile

https://github.com/lonelyplanet/backpack-ui/blob/master/src/components/takeover/index.jsx

**Comment by jcreamer898** [comment]
@nickfranciosi ^

**Comment by thomasthesecond** [comment]
Both are used in production for filtering here:

https://www.lonelyplanet.com/usa/new-york-city/attractions/a/poi-sig/362079

**Comment by jcreamer898** [comment]
I think @nickfranciosi's issue with the Modal is that it wasn't really "responsive". We're kinda swapping out components IIRC no?

**Comment by thomasthesecond** [comment]
Yeah, Modal on desktop changes to Takeover on mobile. Both components kind of do the same thing, but Takeover is more mobile-friendly.

**Comment by nickfranciosi** [comment]
@thomasthesecond @jcreamer898 maybe we can talk through this tomorrow after we talk about profile. I wasn't aware of the Takeover component, so I do have a working responsive version of the modal, but I am fine swapping components

**Comment by jcreamer898** [comment]
I don't really WANT to swap components. That implies the app has knowledge of it being "mobile" or not, unless we render both and swap them which I'd rather not do going forward.

**Comment by thomasthesecond** [comment]
I think the app needs to know one way or another if it's mobile or desktop; I think that's the nature of our stuff being responsive. Instead of having the logic in the app, we have it in each component in the form of media queries. It feels messy to me to have media queries in components; it makes them harder to maintain and less re-usable. My gut feeling is that they shouldn't be there, but I don't know what the right answer is regarding mobile vs. desktop views. It's especially difficult when the mobile and desktop version of the same component are so different, for example the filtering on POIs.

**Comment by jcreamer898** [comment]
>  It's especially difficult when the mobile and desktop version of the same component are so different, for example the filtering on POIs.

If that's the case we need to see WHY they're so different.

I'm confused about why it's bad for a component to have its own media queries. It's no different then how like the Food and Drink or Top Experiences component work in Rizzo Next am I wrong?

**Comment by jcreamer898** [comment]
I just don't want to user agent sniff like we did in dotcom-pois. If we do it other ways that's fine.

**Comment by nickfranciosi** [comment]
@jcreamer898 you wouldn't need to agent sniff, but just swap components based on window size

**Comment by thomasthesecond** [comment]
I think sometimes it's inevitable that mobile and desktop designs are different because of features and/or constraints. But I agree we should try to make things the same across all devices when possible. I also agree about using the user agent, I don't think that's the answer, but we could use `window.matchMedia`.

I wouldn't say it's bad to have media queries in components, but I think media queries remove the component's independence. I think media queries closely couple the component to the app, and if what we say is mobile changes, then we have to update every component. However, I think media queries could be ok if we shift away from the mobile-tablet-desktop mentality and change the component at whichever breakpoint is suited best for it.

I understand it will be difficult to manage a mobile and desktop version of every component. I don't know if that's the right answer, however, I think that would help simplify some components if they didn't have all the logic for context switching.

We can also use props to change the size of components, for example the [MoreLink](https://github.com/lonelyplanet/backpack-ui/blob/master/src/components/moreLink/index.jsx). It doesn't have media queries but it can render 13px or 11px if you pass `size=small`. This allows the component to be small on desktop or large on mobile. If the app wants it to be small on mobile, then it should tell the component that via the `size` prop.

But overall, I think it's up the to app to decide which components to use and how to use them. The components, in my opinion, shouldn't contain layout-specific logic and shouldn't know anything about the screen width.

I haven't really seen anyone talk about media queries in components, yet everyone seems to be building component libraries. I definitely will continue to research this.

**Comment by thomasthesecond** [comment]
There's a fairly new concept called element queries, which could be the answer, but it's not been standardized.

**Comment by jcreamer898** [comment]
>  However, I think media queries could be ok if we shift away from the mobile-tablet-desktop mentality and change the component at whichever breakpoint is suited best for it.

that sounds nice
